version: '3.8'
services:
  dbcluster:
    image: mongo:latest
    container_name: dbcluster
    command: /home/scripts/setup.sh
    depends_on:
      - shard1a
      - shard1b
      - shard1c
      - shard2a
      - shard2b
      - shard2c
      - mongos1
      - mongos2
    volumes:
      - "./scripts:/home/scripts"

  shard1a:
    image: mongo:latest
    container_name: shard1a
    restart: always
    command:
      - --config
      - /etc/mongod.conf
    expose:
      - 27017
    volumes:
      - "./configs/shard1.conf:/etc/mongod.conf"
      - "./scripts/mongo/setup/shard.js:/docker-entrypoint-initdb.d/01.js"
  shard1b:
    image: mongo:latest
    container_name: shard1b
    restart: always
    command:
      - --config
      - /etc/mongod.conf
    expose:
      - 27017
    volumes:
      - "./configs/shard1.conf:/etc/mongod.conf"
      - "./scripts/mongo/setup/shard.js:/docker-entrypoint-initdb.d/01.js"
  shard1c:
    image: mongo:latest
    container_name: shard1c
    restart: always
    command:
      - --config
      - /etc/mongod.conf
    expose:
      - 27017
    volumes:
      - "./configs/shard1.conf:/etc/mongod.conf"
      - "./scripts/mongo/setup/shard.js:/docker-entrypoint-initdb.d/01.js"

  shard2a:
    image: mongo:latest
    container_name: shard2a
    restart: always
    command:
      - --config
      - /etc/mongod.conf
    expose:
      - 27017
    volumes:
      - "./configs/shard2.conf:/etc/mongod.conf"
      - "./scripts/mongo/setup/shard.js:/docker-entrypoint-initdb.d/01.js"
  shard2b:
    image: mongo:latest
    container_name: shard2b
    restart: always
    command:
      - --config
      - /etc/mongod.conf
    expose:
      - 27017
    volumes:
      - "./configs/shard2.conf:/etc/mongod.conf"
      - "./scripts/mongo/setup/shard.js:/docker-entrypoint-initdb.d/01.js"
  shard2c:
    image: mongo:latest
    container_name: shard2c
    restart: always
    command:
      - --config
      - /etc/mongod.conf
    expose:
      - 27017
    volumes:
      - "./configs/shard2.conf:/etc/mongod.conf"
      - "./scripts/mongo/setup/shard.js:/docker-entrypoint-initdb.d/01.js"

  cfgsvr1:
    image: mongo:latest
    container_name: cfgsvr1
    restart: always
    command:
      - --config
      - /etc/mongod.conf
    expose:
      - 27017
    volumes:
      - "./configs/cfgsvr.conf:/etc/mongod.conf"
  cfgsvr2:
    image: mongo:latest
    container_name: cfgsvr2
    restart: always
    command:
      - --config
      - /etc/mongod.conf
    expose:
      - 27017
    volumes:
      - "./configs/cfgsvr.conf:/etc/mongod.conf"
  cfgsvr3:
    image: mongo:latest
    container_name: cfgsvr3
    restart: always
    command:
      - --config
      - /etc/mongod.conf
    expose:
      - 27017
    volumes:
      - "./configs/cfgsvr.conf:/etc/mongod.conf"

  mongos1:
    container_name: mongos1
    image: mongo:latest
    restart: always
    entrypoint: mongos --config /etc/mongos.conf
    depends_on:
      - cfgsvr1
      - cfgsvr2
      - cfgsvr3
    expose:
      - 27017
    ports:
      - 3001:27017
    volumes:
      - "./configs/mongos.conf:/etc/mongos.conf"
  mongos2:
    container_name: mongos2
    image: mongo:latest
    restart: always
    entrypoint: mongos --config /etc/mongos.conf
    depends_on:
      - cfgsvr1
      - cfgsvr2
      - cfgsvr3
    expose:
      - 27017
    ports:
      - 3002:27017
    volumes:
      - "./configs/mongos.conf:/etc/mongos.conf"